version: '3.7'
services:
   micro-service-rnp:
    build:
      args:
        user: cajui
        uid: 1000
      context: ./docker-compose/micro-service-rnp
      dockerfile: Dockerfile
    image: micro-service-rnp
    working_dir: /micro-service-rnp
    volumes:
      - ./:/micro-service-rnp
    
    command: php /micro-service-rnp/yii hello/index  #tail -f /dev/null #php -f /usr/src/app/consumer.php   
   
